import { addDays } from './dates';
import { resolveGateCategory } from './serviceMetadata';
import type { Branch, Service, TimeSlot } from '../types';

export const DEMO_BRANCHES: Branch[] = [
  {
    id: 'br-dxb',
    name: 'Browz 1',
    city: 'Umm Suqeim',
    address: 'Al Wasl Road, Opposite ENOC Petrol Station, Umm Suqeim 3, Dubai, UAE',
    phone: '600 564 668',
    hours: {
      Sun: '9:00 AM–9:00 PM',
      Mon: '9:00 AM–9:00 PM',
      Tue: '9:00 AM–9:00 PM',
      Wed: '9:00 AM–9:00 PM',
      Thu: '9:00 AM–9:00 PM',
      Fri: '9:00 AM–9:00 PM',
      Sat: '9:00 AM–9:00 PM',
    },
    categories: ['Facials', 'Brows, Lips & Lashes', 'Advanced Skin', 'SPMU', 'Grooming'],
    status: 'busy',
  },
  {
    id: 'br-dxb-clinic',
    name: 'Browz 2',
    city: 'Umm Suqeim',
    address: 'Al Wasl Road, Opposite ENOC Petrol Station, Umm Suqeim 3, Dubai, UAE',
    phone: '600 564 668',
    hours: {
      Sun: '9:00 AM–9:00 PM',
      Mon: '9:00 AM–9:00 PM',
      Tue: '9:00 AM–9:00 PM',
      Wed: '9:00 AM–9:00 PM',
      Thu: '9:00 AM–9:00 PM',
      Fri: '9:00 AM–9:00 PM',
      Sat: '9:00 AM–9:00 PM',
    },
    categories: ['Facials', 'Brows, Lips & Lashes', 'Advanced Skin', 'Medical', 'SPMU'],
    status: 'open',
  },
  {
    id: 'br-auh',
    name: 'Browz AD',
    city: 'Saadiyat Island',
    address: 'Jumeirah Saadiyat Hotel Spa, Abu Dhabi, UAE',
    phone: '600 564 668',
    hours: {
      Sun: '9:00 AM–9:00 PM',
      Mon: '9:00 AM–9:00 PM',
      Tue: '9:00 AM–9:00 PM',
      Wed: '9:00 AM–9:00 PM',
      Thu: '9:00 AM–9:00 PM',
      Fri: '9:00 AM–9:00 PM',
      Sat: '9:00 AM–9:00 PM',
    },
    categories: ['Facials', 'Brows, Lips & Lashes', 'Advanced Skin', 'Medical', 'SPMU'],
    status: 'open',
  },
];

function makeService(service: Omit<Service, 'gateCategory'>): Service {
  return {
    ...service,
    gateCategory: resolveGateCategory(service),
  };
}

export const DEMO_SERVICES: Service[] = [
  makeService({
    id: 's-001',
    name: 'Brow Threading',
    category: 'Brows',
    serviceTier: 'T1',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 60,
    priceAed: 80,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: null,
    frequencyHardBlock: false,
    description: 'Precision brow shaping for a clean, defined finish.',
  }),
  makeService({
    id: 's-011',
    name: 'Brow Lamination',
    category: 'Brows, Lips & Lashes',
    serviceTier: 'T1',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 60,
    priceAed: 180,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: 6,
    frequencyHardBlock: false,
    description: 'A sculpting treatment for fuller, brushed-up brows.',
  }),
  makeService({
    id: 's-012',
    name: 'Lip Blush',
    category: 'SPMU',
    serviceTier: 'T2',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 120,
    priceAed: 1400,
    requiresConsultation: true,
    requiresPatchTest: true,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: 42,
    frequencyHardBlock: false,
    description: 'Semi-permanent lip colour treatment.',
  }),
  makeService({
    id: 's-004',
    name: 'Nano Brows',
    category: 'SPMU',
    serviceTier: 'T2',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 120,
    priceAed: 1100,
    requiresConsultation: true,
    requiresPatchTest: true,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: 42,
    frequencyHardBlock: false,
    description: 'Machine-based semi-permanent brow artistry.',
  }),
  makeService({
    id: 's-021',
    name: 'Eyeliner SPMU',
    category: 'SPMU',
    serviceTier: 'T2',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 90,
    priceAed: 1200,
    requiresConsultation: true,
    requiresPatchTest: true,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: 42,
    frequencyHardBlock: false,
    description: 'Semi-permanent eyeliner enhancement.',
  }),
  makeService({
    id: 's-007',
    name: 'Profhilo',
    category: 'Medical',
    serviceTier: 'T3',
    city: 'Abu Dhabi',
    durationMinutes: 30,
    priceAed: 1500,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: true,
    isMedicalGated: true,
    minFrequencyWeeks: 24,
    frequencyHardBlock: true,
    description: 'Injectable bio-remodelling treatment.',
  }),
  makeService({
    id: 's-008',
    name: 'Morpheus8',
    category: 'Medical',
    serviceTier: 'T3',
    city: 'Abu Dhabi',
    durationMinutes: 60,
    priceAed: 1800,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: true,
    isMedicalGated: true,
    minFrequencyWeeks: 12,
    frequencyHardBlock: true,
    description: 'Energy-based skin remodelling treatment.',
  }),
  makeService({
    id: 's-009',
    name: 'Laser Resurfacing',
    category: 'Medical',
    serviceTier: 'T3',
    city: 'Abu Dhabi',
    durationMinutes: 60,
    priceAed: 1600,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: true,
    isMedicalGated: true,
    minFrequencyWeeks: 12,
    frequencyHardBlock: true,
    description: 'Medical laser treatment for texture and tone.',
  }),
  makeService({
    id: 's-005',
    name: 'HydraFacial',
    category: 'Facials',
    serviceTier: 'T1',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 60,
    priceAed: 500,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: 4,
    frequencyHardBlock: false,
    description: 'A hydrating facial with deep cleansing and glow support.',
  }),
  makeService({
    id: 's-900',
    name: 'Aesthetic Face and Skin Consultation',
    category: 'Advanced Skin',
    serviceTier: 'T1',
    city: 'Dubai · Abu Dhabi',
    durationMinutes: 30,
    priceAed: 0,
    requiresConsultation: false,
    requiresPatchTest: false,
    requiresScreening: false,
    isMedicalGated: false,
    minFrequencyWeeks: null,
    frequencyHardBlock: false,
    description: 'A complimentary consultation to plan the right treatment journey.',
  }),
];

export function buildDemoSlots(date = new Date()): TimeSlot[] {
  const day = date.toISOString().slice(0, 10);
  const serviceId = DEMO_SERVICES[0]?.id ?? '';
  const branchId = DEMO_BRANCHES[0]?.id ?? '';

  return ['09:00', '10:00', '11:30', '13:00', '15:00', '17:30'].map((time, index) => {
    const startTime = `${day}T${time}:00.000Z`;
    const endHour = String(Number(time.slice(0, 2)) + 1).padStart(2, '0');

    return {
      id: `slot-demo-${index + 1}`,
      branchId,
      serviceId,
      artistId: null,
      startTime,
      endTime: `${day}T${endHour}:${time.slice(3)}:00.000Z`,
      status: 'available',
    };
  });
}

export const DEMO_FAQS = [
  {
    question: 'What are your opening hours?',
    answer: 'Our branches are open daily from morning until evening, and exact hours can vary slightly by location.',
    category: 'booking',
  },
  {
    question: 'Do I need a patch test for SPMU?',
    answer: 'Yes, SPMU services require a consultation and patch test before treatment can be confirmed.',
    category: 'services',
  },
  {
    question: 'Where are you located?',
    answer: 'Browz currently serves guests in Umm Suqeim, Dubai and Saadiyat Island, Abu Dhabi.',
    category: 'services',
  },
];
